# install: conda env create -f environment.yml
# update:  conda env update -f environment.yml

# for linux, replace
#   - "deeplabcut[gui]"
# with
#   - deeplabcut

name: ephys2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - jupyter
  - nb_conda
  - nb_conda_kernels
  - ffmpeg
  - matplotlib
  - scikit-image
  - xarray
  - tqdm
  - pytables
  - umap-learn
  - pip:
    - deeplabcut[gui,tf]
    - astropy
    - wavio
    - pysimplegui
    - netcdf4
    - opencv-python
    - scipy
    - ray