# FreelyMovingEphys-SBCs


# path to animal directory
animal_directory: /path/to/animal/

main:
  deinterlace: true
  undistort: true
  pose_estimation: true
  parameters: true
  ephys: true

paths:
  # worldcam video of checkerboard
  worldcam_checkerboard: E:/freely_moving_ephys/camera_calibration_params/betafpv_checkerboard.avi
  sidecam_checkerboard: E:/freely_moving_ephys/camera_calibration_params/012822_checkerboard_control_SIDE_0.avi
  # npz of worldcam properties
  # if define_worldcam_distortion is True, this file will be written (and possibly overwritten)
  # if undistort is False, this file will be read
  worldcam_mtx: E:/freely_moving_ephys/camera_calibration_params/world_checkerboard_calib.npz
  sidecam_mtx: E:/freely_moving_ephys/camera_calibration_params/side_checkerboard_calib.npz
  # paths to dlc project config.yaml files
  dlc_projects:
    REYE: E:/freely_moving_ephys/deeplabcut_projects/EphysEyeCams8-dylan-2021-10-12/config.yaml
    TOP1: E:/freely_moving_ephys/deeplabcut_projects/EphysTopCam2-dylan-2021-11-16/config.yaml
  # channel maps json
  channel_map_path: C:/Users/Niell Lab/Documents/GitHub/FreelyMovingEphys/config/channel_maps.json

options:
  # list of recordings to process
  # if the list is empty, all subdirectories will be processed
  recording_list: []
  # ephys unit to highlight
  neuron_to_highlight: 0
  # ephys probe type
  # options = [default16, NN_H16, default64, NN_H64-LP, DB_P64-3, DB_P64-8, DB_P128-6])
  probe: default16
  # write ephys videos
  ephys_videos: false

internals:
  # delete existing .h5 and .pickle files saved out from previous DLC analysis
  clear_dlc: false
  # flip eye and world cameras without deinterlacing
  # can only be used if deinterlace is false
  flip_headcams:
    run: false
    hflip: true
    vlip: true
  # apply an automatic contrast correction to the eyecam videos, getting a gamma value frame-by-frame
  # good for a dark, low-contrast video (slow)
  apply_gamma_to_eyecam: false
  # dlc eyecam network has the reflection of the ir light labeled?
  eye_has_reflection: true
  # dlc eyecam network has both corners of the eye (tear duct) labeled?
  eye_has_corners: true
  eye_corners_first: false
  # whether or not to subtract the center of the ir spot's reflection on the eye from the labeled points around the eye
  subtract_reflection_position: true
  # pupil cyclotorsion
  get_torsion_from_ridges: false
  get_torsion_from_markers: false
  # excise frames surrounding gaps in eye and world timestamps (win size +/- 3 frames) to accomodate dropped data
  drop_window_around_missing_data: false
  # only use animal subdirectories that contain fm or hf
  # if false, all subdirectories will be processed
  follow_strict_directory_naming: true
  # use exact file nomenclature
  # if false, requirements will be relaxed but multiple files may be returned when looking (i.e. deinterlaced and raw videos may be confused)
  follow_strict_naming: true
  # change behavior for eyecam calibration parameter use
  # if auto, fm will write calibration values and hf recordings will read calibration values from fm for the same session
  # if self, all recordings will use and save their own values for calibration
  force_eyecam_calibration_params: auto
  # save diagnostic videos out of preprocessing?
  diagnostic_preprocessing_videos: true